<?xml version="1.0" encoding="UTF-8"?>
<!-- 19. Create an internal and External DTD of a valid xml. (Take any valid xml example) -->
<!-- Internal DTD -->
 <!DOCTYPE message [
 <!ELEMENT message (to, from, subject, body)>
 <!ELEMENT to (#PCDATA)>
 <!ELEMENT from (#PCDATA)>
 <!ELEMENT subject (#PCDATA)>
 <!ELEMENT body (#PCDATA)>
 ]>

 <message>
    <to>Abi</to>
    <from>Abinash</from>
    <subject>About Dashain Vacation</subject>
    <body>How was your Dashain Vacation?</body>
 </message>